dist: xenial
before_install:
- sudo apt-get install -y ruby ruby-dev rubygems build-essential make libffi-dev devscripts
- sudo gem install -n /usr/local/bin --no-ri --no-rdoc fpm
addons:
  apt:
    update: true
script:
- sudo make
deploy:
  provider: bintray
  file: build/packages/descriptor.json
  user: asten
  key:
    secure: I1zuH8AHoiB4+YkxPhBUSDWTsJGZEKO1P6l2BfowGzJollLPM2xHDDXjZ9CMXyBZ7NRlcGP0sZwH6osqiaojIEPVpx8gFyKWJHert5oz/9fdH9ikittgrF8aCBjRZDChBGhTVaSAXD/TMmbJrRj1iJAGiwnsTnJik1cbFy8gaEu4M3OkqY6K+E+BZom3QAxl/awSwsDy1w80haEs4yl+PlnU8HBFnHkEQO9eUGyxn1vlRFcuUugeSwrRp3EMYh39cxqsl3fCADsL3O/8KqIQyRlnvODPCzWcRS6EyLJBauiS/2goh19eZ0calQ0zzTD33zWJD8auE4aKTtfWNj4uBJgvqrfCrl1ZWTt4kGtiOlmUsnUshLVsIyKskTBP1S97Z8+Wz2H8LMKB61I1ei8AMCbQgewSy8kFJcnWG8Bp0S0Noh8pmRGimD9nwiM8yroFarZ/U0PrQ1EUi5bV0nlhqUoBC3X9hoQoFoNH9ZI783xXHG45BmWVSQqm4oPkgG0cJKaZFta4thn+fYHaOo7kQWd74IBhi7ovbMPq86pO8ZC3uPt43kWFoWkpjtV/l7nz9XcCiCfc+fEm24w3Ik5e6L7xhoTwgrC10Xb2OiQMP4UpuYvW6DQc1NPUmabcTPB+JKN79q5jYWnav/BJxZfWiT5V8ChYT+DSXpKxcGngwBU=
  skip_cleanup: true
